# Generated by Django 4.2.1 on 2023-05-31 18:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('Entrant', 'Entrant'), ('Sortant', 'Sortant')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingExit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('freed_location', models.CharField(max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('parking_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parking.parkingentry')),
            ],
        ),
        migrations.AddField(
            model_name='parkingentry',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.vehicle'),
        ),
        migrations.AddConstraint(
            model_name='parkingentry',
            constraint=models.UniqueConstraint(fields=('location', 'status'), name='unique_location_status'),
        ),
    ]
