# Generated by Django 4.2.1 on 2023-05-31 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingexit',
            old_name='freed_location',
            new_name='location_freed',
        ),
        migrations.RemoveField(
            model_name='parkingexit',
            name='price',
        ),
    ]
