# Generated by Django 4.2.1 on 2023-05-31 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_rename_freed_location_parkingexit_location_freed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingexit',
            old_name='location_freed',
            new_name='freed_location',
        ),
        migrations.AddField(
            model_name='parkingexit',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
